# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dca38da6224063f59ebb2e964c51fa1986d8b22371703207618dd4f5b3b266cf3f7550e3ad05631f9e39db79e172a3b877f80dc045620fe54485a753bbf30963

test:
  secret_key_base: 228cf076deaca6f4ddbc06ba258eeb6f2986770b5bc9982857f78f030f1289e6e670a41c273468738575bb763c2cef54c34597a8cb0ec89bdbc86e3cfafb9e55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
